package org.frangoro.domain;
// Generated 06-jul-2016 19:31:57 by Hibernate Tools 5.0.0.Alpha3

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ItemsTransLoc generated by hbm2java
 */
@Entity
@Table(name = "ITEMS_TRANS_LOC")
public class ItemsTransLoc implements java.io.Serializable {

	private ItemsTransLocId id;

	public ItemsTransLoc() {
	}

	public ItemsTransLoc(ItemsTransLocId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, precision = 10, scale = 0) ),
			@AttributeOverride(name = "parentId", column = @Column(name = "PARENT_ID", precision = 10, scale = 0) ),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", length = 50) ),
			@AttributeOverride(name = "name", column = @Column(name = "NAME", nullable = false, length = 50) ),
			@AttributeOverride(name = "description", column = @Column(name = "DESCRIPTION", length = 100) ),
			@AttributeOverride(name = "brand", column = @Column(name = "BRAND", length = 50) ),
			@AttributeOverride(name = "model", column = @Column(name = "MODEL", length = 50) ),
			@AttributeOverride(name = "serialNumber", column = @Column(name = "SERIAL_NUMBER", length = 50) ),
			@AttributeOverride(name = "features", column = @Column(name = "FEATURES", length = 200) ),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", nullable = false, length = 20) ),
			@AttributeOverride(name = "location", column = @Column(name = "LOCATION", length = 50) ) })
	public ItemsTransLocId getId() {
		return this.id;
	}

	public void setId(ItemsTransLocId id) {
		this.id = id;
	}

}
