package org.frangoro.domain;
// Generated 06-jul-2016 19:31:57 by Hibernate Tools 5.0.0.Alpha3

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Locations generated by hbm2java
 */
@Entity
@Table(name = "LOCATIONS")
public class Locations implements java.io.Serializable {

	private long id;
	private String name;
	private String address;
	private Set transactionses = new HashSet(0);

	public Locations() {
	}

	public Locations(long id) {
		this.id = id;
	}

	public Locations(long id, String name, String address, Set transactionses) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.transactionses = transactionses;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ADDRESS", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locations")
	public Set getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set transactionses) {
		this.transactionses = transactionses;
	}

}
