package org.frangoro.domain;
// Generated 06-jul-2016 14:46:01 by Hibernate Tools 5.0.0.Alpha3

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemsTransLocId generated by hbm2java
 */
@Embeddable
public class ItemsTransLocId implements java.io.Serializable {

	private long id;
	private Long parentId;
	private String code;
	private String name;
	private String description;
	private String brand;
	private String model;
	private String serialNumber;
	private String features;
	private String status;
	private String location;

	public ItemsTransLocId() {
	}

	public ItemsTransLocId(long id, String name, String status) {
		this.id = id;
		this.name = name;
		this.status = status;
	}

	public ItemsTransLocId(long id, Long parentId, String code, String name, String description, String brand,
			String model, String serialNumber, String features, String status, String location) {
		this.id = id;
		this.parentId = parentId;
		this.code = code;
		this.name = name;
		this.description = description;
		this.brand = brand;
		this.model = model;
		this.serialNumber = serialNumber;
		this.features = features;
		this.status = status;
		this.location = location;
	}

	@Column(name = "ID", nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "PARENT_ID", precision = 10, scale = 0)
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "CODE", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "BRAND", length = 50)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "MODEL", length = 50)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "SERIAL_NUMBER", length = 50)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "FEATURES", length = 200)
	public String getFeatures() {
		return this.features;
	}

	public void setFeatures(String features) {
		this.features = features;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "LOCATION", length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemsTransLocId))
			return false;
		ItemsTransLocId castOther = (ItemsTransLocId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getParentId() == castOther.getParentId()) || (this.getParentId() != null
						&& castOther.getParentId() != null && this.getParentId().equals(castOther.getParentId())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null
						&& this.getCode().equals(castOther.getCode())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getBrand() == castOther.getBrand()) || (this.getBrand() != null
						&& castOther.getBrand() != null && this.getBrand().equals(castOther.getBrand())))
				&& ((this.getModel() == castOther.getModel()) || (this.getModel() != null
						&& castOther.getModel() != null && this.getModel().equals(castOther.getModel())))
				&& ((this.getSerialNumber() == castOther.getSerialNumber())
						|| (this.getSerialNumber() != null && castOther.getSerialNumber() != null
								&& this.getSerialNumber().equals(castOther.getSerialNumber())))
				&& ((this.getFeatures() == castOther.getFeatures()) || (this.getFeatures() != null
						&& castOther.getFeatures() != null && this.getFeatures().equals(castOther.getFeatures())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getLocation() == castOther.getLocation()) || (this.getLocation() != null
						&& castOther.getLocation() != null && this.getLocation().equals(castOther.getLocation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (getParentId() == null ? 0 : this.getParentId().hashCode());
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getBrand() == null ? 0 : this.getBrand().hashCode());
		result = 37 * result + (getModel() == null ? 0 : this.getModel().hashCode());
		result = 37 * result + (getSerialNumber() == null ? 0 : this.getSerialNumber().hashCode());
		result = 37 * result + (getFeatures() == null ? 0 : this.getFeatures().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
		return result;
	}

}
